feat: Add redis to keramik
3box/keramik pull request #75
Opened 2023-09-01 14:41 UTC by dbcfd

2023-09-01 14:48 UTC, smrz2001 approved these changes
🚀

2023-09-01 14:48 UTC, smrz2001 commented on operator/src/network/redis.rs
> +                    image_pull_policy: Some("Always".to_string()),
Not a big deal but should we change this to IfNotPresent since it's unlikely to change much?

2023-09-05 16:51 UTC, nathanielc requested changes
Change looks good, However I have a design question.

Why is the redis service/stateful set added to the network CRD and not the simulation CRD? 

Seems like the use case is to allow worker jobs to communicate global state via redis. Do we need redis to be part of the network in that case? 

Is it because we want Redis to outlive the simulation? If so I'd like to understand that case. 

As we move keramik closer to being used to deploy production networks I want to make sure the performance testing use case remains well isolated from the deployment use case.

2023-09-06 16:32 UTC, dbcfd commented
> Change looks good, However I have a design question.
> 
> Why is the redis service/stateful set added to the network CRD and not the simulation CRD?
> 
> Seems like the use case is to allow worker jobs to communicate global state via redis. Do we need redis to be part of the network in that case?
> 
> Is it because we want Redis to outlive the simulation? If so I'd like to understand that case.
> 
> As we move keramik closer to being used to deploy production networks I want to make sure the performance testing use case remains well isolated from the deployment use case.

I went back and forth on this, but it felt more like it belonged at the network layer, given that ceramic/CAS live at the network layer, and this is a service that simulations depend on. I could also see the services actually using redis at some point for caching/sharing state. 

Should it be optional at network layer, or just part of simulation layer?

2023-09-07 19:03 UTC, nathanielc approved these changes
LGTM with the left over changes to the network stub removed.

2023-09-07 19:03 UTC, nathanielc commented on operator/src/network/stub.rs
> +    pub ceramic_service: ExpectPatch<ExpectFile>,
These fields are never used. Should we remove them?

2023-09-08 00:11 UTC, merged